---
name: Tidewave JavaScript issue
description: File a bug report related to Tidewave JavaScript CLI or MCP server

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report.

  - type: input
    id: os
    attributes:
      label: What is your operating system?
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: What is your Node.js version?
    validations:
      required: true

  - type: input
    id: runtime
    attributes:
      label: What JavaScript runtime are you using?
      description: e.g., Node.js, Bun, Deno
    validations:
      required: true

  - type: input
    id: tidewave-version
    attributes:
      label: What is your Tidewave version?
    validations:
      required: true

  - type: input
    id: command
    attributes:
      label: Which Tidewave command are you using?
      description: e.g., "npx tidewave docs", "npx tidewave mcp --stdio", "bunx tidewave source"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: >
        If reporting a bug, please include errors, stacktraces, and reproducing steps.
        For MCP issues, include your editor/client configuration.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A short description on how you expected it to behave.
    validations:
      required: true
